version: "3.8"

services:
  nodecrudusers:
    container_name: nodebackendusers
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - crudusersnetwork

networks:
  crudusersnetwork:
    external: true
