version: "3.8"

services:
  app:
    container_name: nodecrudusers
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    networks:
      - crudusersnetwork

networks:
  crudusersnetwork:
    external: true
